### ISSUE TITLE
Autoload doesn't seem to work?

### ISSUE THREAD

**Issue by tmikaeld** [dlin-me/saasu#2]
I installed the package, and added the require:

``` php
require 'vendor/autoload.php';
```

But i only get this error:
PHP Fatal error:  Class 'SaasuAPI' not found.

I'm new to composer, so how do i debug this?

**Comment by tmikaeld** [comment]
Also, it seems like resources are installed twice.

Guzzle is in:
/vendor/guzzle
/vendor/dlin/saasu/vendor/guzzle

symphony is in:
/vendor/symphony
/vendor/dlin/saasu/vendor/symphony

**Comment by dlin-me** [comment]
No, it should install once in the vendor lib. Do not run composer inside the lib again. 

Can you tell me how do you use the class ? did you use namespace ? example:

<?php
include __DIR__."/../vendor/autoload.php";

use Dlin\Saasu\SaasuAPI;

$api = new SaasuAPI($key, $file);

**Comment by tmikaeld** [comment]
I think it's because you have these in your repository:
/vendor/dlin/saasu/vendor/guzzle
/vendor/dlin/saasu/vendor/symphony

It was the namespace that made the difference.

Do i need to namespace every class? Because now i get this:
Class 'InventoryItem' not found

**Comment by tmikaeld** [comment]
Nevermind, i'm starting to understand the structure now.

``` php
use Dlin\Saasu\Entity\InventoryItem;
use Dlin\Saasu\Entity\FullInventoryItemCriteria;
```

Thanks for the help!
This should probably be added to the readme to make it clear for noobs like me ;-)
