### ISSUE TITLE
Is there any way to get all invoices for a particular FileUId and Accesskey?

### ISSUE THREAD

**Issue by adityadr** [dlin-me/saasu#4]
When i am using this URL to get an Invoice for a particular UId,
URL:
https://secure.saasu.com/webservices/rest/r1/Invoice?wsaccesskey={wsaccesskey}&amp;FileUid={FileUid}&amp;uid={uid}

Is it possible if I can get all the InvoiceUids for a combination of Wsaccesskey and FileUid ?
If you could just tell me what parameter to use while sending the GET , its a really helpful Saasu PHP Client

Really Appreciate any help, thanks in advance!

**Comment by dlin-me** [comment]
Hi, the Saasu PHP Client works with one FileUid at a time. Getting all invoices with a given FileUid is just one of many common tasks the client can achieve. 

To list all invoices for a FileUid+Accesskey:

```
$api = new SaasuAPI($wsaccesskey, $fileUid);
$invoices = $api->searchEntities(new InvoiceCriteria());
```

The returned $invoices is an array of Invoice objects. Is this what you need ?

**Comment by adityadr** [comment]
Thanks i got the GET request parameters , was really helpful: i was looking for this:
https://secure.saasu.com/webservices/rest/r1/invoicelist?wsaccesskey={WSAccessKey}&FileUid={FileUid}&TransactionType=p&PaidStatus=paid

**Comment by dlin-me** [comment]
You can do this

$invoiceCriteria = new InvoiceCriteria()
$invoiceCriteria->transactionType = ’P’;
$invoiceCriteria->paidStatus = ‘Paid’;

$api->searchEntities($invoiceCriteria);

**Comment by adityadr** [comment]
Thanks a lot, 
I was wondering if there is any way we could fetch Attachments for a Purchase Invoice using GET/POST Saasu API or using your Saasu PHP Client with the help of File Id , AccessKey and Invoice Uid ? 
Could not find much in http://help.saasu.com/api/
